### ISSUE TITLE
Alexa integration

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#1015]

**Comment by thatguyza** [comment]
Can't wait for this, thanks @doom369

**Comment by nilavachowdhury** [comment]
wow! Will this feature really make into blynk!?

**Comment by doom369** [comment]
@nilavachowdhury at some point - sure. No estimates yet. This integration is really expensive in terms of resources and time required.

**Comment by d4v3y0rk** [comment]
This works to integrate Alexa and Blynk. Since they have an HTTP endpoint for setting and getting info from blynk-cloud you can't use that endpoint with an Alexa skill but you can hit it with lambda. The really basic lambda function handles requests and returns text to Alexa. 
https://github.com/d4v3y0rk/blynk-alexa-lambda

**Comment by doom369** [comment]
Thanks. Will take a look when I have a time.

**Comment by doom369** [comment]
Will be implemented as the part of new Blynk Platform
