### ISSUE TITLE
Can we have a server 0.41.17 java 8 version fix too?

### ISSUE THREAD

**Issue by rtorrescodes** [blynkkk/blynk-server#1422]
Hi there, thanks for the 0.41.17 version but, some of us still using the java 8 version.
¿Can you make the fix for that version too? thanks a lot.

**Comment by doom369** [comment]
Sorry. Java 8 is out of date and no longer supported. You need to use Java 17 or Java 11 at least.

**Comment by MichaIng** [comment]
This is a problem for many Raspberry Pi 1 and Zero users, since for this armv6hf architecture there is only a functional Java 8 build available while all newer builds required ARMv7 at least. The Raspberry Pi Zero is still an extremely popular SBC, one of the (still) most used Raspberry Pi models, due to its small form factor and price, for small home server projects. Since Log4Shell is such a major and easy to (mis)use security vulnerability, if there is any chance to add a last Java 8 build, this would be highly welcome and allow a lot of users to secure their Blynk server.
