### ISSUE TITLE
Invalid auth token

### ISSUE THREAD

**Issue by wes1993** [blynkkk/blynk-server#1431]
Hello,
I'm trying to create a new project in my local Blynk Server, from the app.
I can create the project and i will receive the token to my email but if a access to admin webpage i can't see the project and also if i try to flash the FW i will receive the Invalid auth token error..
I have read in the logs folder but unfortunately nothing useful i have found...

Best Regards
Stefano

**Comment by Peterkn2001** [comment]
My guess is that you haven't entered your local server IP and port into the custom server settings of the app before creating the account, so the account has been created on the Blynk cloud server rather than your local server.

Did you follow this part of the instructions...
https://github.com/blynkkk/blynk-server#app-and-sketch-changes

Also, you won't get an email from your local server unless you have configured email correctly (which is quite tricky thanks to gmail) and when you do receive the email it will be from the gmail address that you created, not from `dispatcher@blynk.io`

You can work around the lack of email by viewing the token in the app and sending it to yourself via your own email client on the device.

Pete.

**Comment by wes1993** [comment]
Thanks for your reply @Peterkn2001 
I have configured my Gmail infact i have received the api from my Gmail account.
I have another Blynk application that run in my local server without problem... i don't know why i can't create a second project..

Best Regards
Stefano

**Comment by Peterkn2001** [comment]
It’s difficult to help if you drip-feed snippets of information and include partial screenshots that leave people guessing about the rest of your setup.

I’d recommend providing as much information as possible, with as many detailed screenshots as possible.

I’d also suggest that you share your server.properties file.

Pete.

**Comment by wes1993** [comment]
Thanks again a lot for your reply.
I have inserted a partial Screenshot to hide my emails.
Finally i have fixed the problem i think, i have uninstalled and installed again the mobile app.

Best regards
Stefano

**Comment by wes1993** [comment]
Unfortunately i think i have found a really really bad bug...
After i have removed and reinstalled the APP my old project in my phone it's offline, in the phone of my wife is online... same auth id etc...

https://user-images.githubusercontent.com/52070589/156050273-f593c3ea-b952-4a4c-99a3-012875b648f6.mp4

Could you help me please?

Best Regards
Stefano

**Comment by Peterkn2001** [comment]
Have you restarted the phone?
Ate both phones running the same app version?

Once again, providing more information is likely to elicit more assistance.

Pete.

**Comment by wes1993** [comment]
Sorry @Peterkn2001…
I’m so stupid… I have solved my problem… I have two instance of Blynk on my server with different port… I’m using one instance instead of another… sorry sorry sorry really sorry….

Best Regards
Stefano
