### ISSUE TITLE
Isn't updated device status on the server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#400]
![device-2016-12-20-000629](https://cloud.githubusercontent.com/assets/16590099/21331026/1dfe1950-c649-11e6-812c-fbc4ae49e5be.png)
REST:
``` 
"devices":
    [
        {
            "id": 0,
            "name": "Arduino Nano",
            "boardType": "Arduino Nano",
            "token": "TOKEN",
            "connectionType": "WI_FI",
            "status": "ONLINE",
            "disconnectTime": 1482094768093
        },
        {
            "id": 1,
            "name": "New Device",
            "boardType": "Intel Edison",
            "token": "TOKEN",
            "connectionType": "BLUETOOTH",
            "disconnectTime": 0
        }
    ] 
```
P.S. Device is offline 100%

**Comment by doom369** [comment]
@Refenz Status update is not real time. Due to technical reasons there is no way to find out that connection was dropped. That's we have `ping` mechanism. Hardware sends every 5 seconds (it could be changed) ping command to server. If server doesn't get 3 ping that means hardware was disconnected. So approximate time for status update is 15 secs.

**Comment by Refenz** [comment]
@doom369 
Passed several hours from the last access to the network.

**Comment by doom369** [comment]
@Refenz ok. I made possible fix. Please try to reproduce again.

**Comment by Refenz** [comment]
@doom369 
Doesn't help.
Device still online.

**Comment by doom369** [comment]
@Refenz Please check one more time.
